flowchart LR

    A(AWS)
    EC2(Cloud Computing solutions)
    

    A --provides--> EC2
    EC2 ==> EC2A(Virtual machine renting EC2)
    EC2 ==> EC2B(Storing data EBS)
    EC2 ==> EC2C(Load distribution ELB)
    EC2 ==> EC2D(Auto-scaling grup ASG)


